### ISSUE TITLE
Multiple python FindSV.py --run required?

### ISSUE THREAD

**Issue by dnil** [J35P312/FindSV#3]
I needed several ```python FindSV.py --run``` to step through the pipeline: once for calling and database, once for filter. The analysis staus stuck on ```ongoing``` although the slurm run was finished. Is this the intended behavior? Dependency chain problem?

**Comment by J35P312** [comment]
One python FindSV.py --run is needed per step of the pipeline. My plan was to add a simple method to let crontab handle the running of the pipeline. However, I did not have the right to edit crontab at uppmax. Instead I have recently added a new mode of running the pipeline:
python FindSV.py --run --cycle n
By using this command the pipeline will automatically be updated every nth hour

The analysis status should not be stuck at ongoing, have you tried re-running the pipeline? Sometimes there is a bit of a lag when communicating with slurm. I will have a look at it if if rerunning the pipeline does not help.
